BelanjaKu/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('hapus-item/<int:id>',hapus_item,name="hapus_item"),
    path('tambah-item/<int:id>',tambah_item,name="tambah_item"),
    path('kurangi-item/<int:id>',kurangi_item,name="kurangi_item"),
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('json/', show_json, name='show_json'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "price","description"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as auth_logout

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)
    
@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseNotFound
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.http import JsonResponse
import json

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'nama':'Zaidan Naufal Ilmi',
        'jumlah_item' : items.count,
        'npm' : '2206081761',
        'class' : 'PBP F',
        'items' : items,
        'last_login': request.COOKIES['last_login'],        
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun anda berhasil dibuat!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response 
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/login')
def tambah_item(request, id):
    item = Item.objects.get(id=id)
    item.amount +=1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def kurangi_item(request,id):
    item = Item.objects.get(id=id)
    if item.amount >0:
        item.amount -=1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required(login_url='/login')
def hapus_item(request,id):
    item =Item.objects.get(id=id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name,price=price, amount=amount,description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="tambah item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><strong>BelanjaKU</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'main:register' %}">
                <button  style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%; border-radius: 8px;border: none;height: 35px;">
                    Register
                </button>
            </a>
          </li>
        </ul>
      </div>
    </div>
</nav>
<div class="container" style="margin-top: 30px;">
    <div class="row">
        <div class="col-4">
            <div class="card" style="border: none;">
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class = "login">

                    <h2 style="text-align: center;">Login</h>

                    <form method="POST" action="">
                            {% csrf_token %}
                            <table style="border:none;margin-right: 10px;margin-top: 10px;">
                                <tr>
                                    <td><p style="font-size: 24px;margin-left: 10px;margin-right: 10px;">Username:</p></td>
                                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                                </tr>
                                        
                                <tr>
                                    <td><p style="font-size: 24px;margin-left: 10px;margin-right: 10px;">Password:</p> </td>
                                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>

                            </table>
                        
            
                            <div class="card-body">         
                                <p class="card-text" style="font-size: 10px;text-align:right;">Don't have an account yet? <a href="{% url 'main:register' %}" style="font-size: 10px">Register Now</a></p>
                                <input class="btn login_btn"  type="submit" value="Masuk" style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%;">
                            </div>
                    </form>   
                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %} 
                </div>
            </div>
    </div>
</div>


{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="atas">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><strong>BelanjaKU</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'main:logout' %}">
                <button style="border-radius: 4px;border:none;color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%;height:35px;margin-top:10px">
                    Logout
                </button>
            </a>
          </li>
        </ul>
      </div>
      <p style="color:black;font-size:18px;" align="right"><strong>User: {{name}}</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
    </div>
  </nav>
</div>
<h4 id ="tulisan" style="color:rgb(50, 59, 218);padding-left: 5vh;padding-top: 6vh;" align="left"></h4>

<div class="row" style="max-height: 60vh;width: 100%;position: relative;padding-left: 5vh;padding-top: 2vh;">
  <div class="col-4">
    <div id="list-example" class="list-group" style="max-height: 35vh;overflow-y: auto;">
    </div>
    <div style="padding-top: 2vh;">
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="padding-top: 2vh;border-radius: 6px;border: none;background-color: rgb(50, 59, 218);color: white;height: 5vh;width: 100%;height: 100%;vertical-align: text-bottom;"><strong>Tambah item baru</strong></button> 
    </div>
  </div>

  <div class="col-8" style="overflow-y: hidden;">
    <div id="scrollable"data-bs-target="#list-example" data-bs-smooth-scroll="true" class="scrollspy" tabindex="0" style="overflow-y: hidden;height: 60vh; scroll-behavior: smooth;">
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah item baru</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form id="form" onsubmit="return false;">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="name" class="col-form-label">Nama item:</label>
                      <input type="text" class="form-control" id="name" name="name"></input>
                  </div>
                  <div class="mb-3">
                      <label for="price" class="col-form-label">Harga:</label>
                      <input type="number" class="form-control" id="price" name="price"></input>
                  </div>
                  <div class="mb-3">
                    <label for="amount" class="col-form-label">Jumlah:</label>
                    <input class="form-control" id="description" name="amount"></input>
                </div>
                  <div class="mb-3">
                      <label for="description" class="col-form-label">Deskripsi:</label>
                      <textarea class="form-control" id="description" name="description"></textarea>
                  </div>
              </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" style="background-color: rgb(50, 59, 218);" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Tambah item</button>
          </div>
      </div>
  </div>
</div>
<p style="padding-top: 0vh;padding-left: 5vh;font-size: 10px;">Oleh: {{ nama }}<br>{{npm}}<br>{{class}}<p style="padding-top: 0vh;padding-right: 5vh;font-size: 10px;"align=right>Terakhir login: {{last_login}}</p></p>

<script>
  async function getProducts() {
      return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
  }

  async function refreshProducts() {
      document.getElementById("list-example").innerHTML = ""
      document.getElementById("scrollable").innerHTML=""
      document.getElementById("tulisan").innerHTML = ""
        const items = await getProducts()
        let htmlBerikutnya =``
        let htmlbaru =``
        let htmlString = ``
        var hitung = 0

        items.forEach((item) => {
            hitung+=1
            htmlString += `\n<a class="list-group-item"  href="#${item.fields.name}"><strong>${item.fields.name}</strong></a>` 
        })
        items.forEach((item)=>{
          htmlBerikutnya += `\n
          <div class="card" id="${item.fields.name}" style="height: 60vh;max-height: 60vh;">
            <h4 style="padding:2vh;font-size: 24;">${item.fields.name}</h4>
            <p style="padding-left: 2vh;">harga: Rp.${item.fields.price} <br> jumlah: ${item.fields.amount}</p>
            <div class="card" style="margin-left: 2vh;overflow-y:auto;margin-right: 2vh;height: 30vh;max-height: 30vh;">
              <p style="padding:2vh;">${item.fields.description}</p>
            </div>
            <div class="btn-group" style="width: 30vh;padding: 2vh;">
              <a href="main:tambah_item/${item.pk}" rel="noreferrer" style= "background-color: rgb(50, 59, 218)"class="btn btn-primary">Tambah</a>
              <a href="main:hapus_item/${item.pk}" rel="noreferrer" style= "background-color: rgb(50, 59, 218)"class="btn btn-primary">Hapus</a>
              <a href="main:kurangi_item/${item.pk}" rel="noreferrer" style= "background-color: rgb(50, 59, 218)"class="btn btn-primary">Kurang</a>
            </div>
          </div>`
        })

        htmlbaru+=`<strong>Anda menyimpan ${hitung} pada aplikasi ini</strong>`    
      document.getElementById("list-example").innerHTML = htmlString
      document.getElementById("scrollable").innerHTML = htmlBerikutnya
      document.getElementById("tulisan").innerHTML = htmlbaru
      function addProduct() {
          fetch("{% url 'main:add_product_ajax' %}", {
              method: 'POST',
              body: new FormData(document.querySelector('#form'))
          }).then(refreshProducts)

          document.getElementById("form").reset()
          return false
      }
      document.getElementById("button_add").onclick = addProduct      
  }

  refreshProducts()
</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Halaman Registrasi</title>
{% endblock meta %}

{% block content %}  
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><strong>BelanjaKU</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'main:login' %}">
                <button  style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%; border-radius: 8px;border: none;height: 35px;">
                    Login
                </button>
            </a>
          </li>
        </ul>
      </div>
    </div>
</nav><div class="container" style="margin-top: 30px;width: 100%;">
    <div class="row">
        <div class="col-3">
            <div class="card" style="border: none;">
            </div>
        </div>
        <div class="col-6">
            <div class="card" style="width: 100%;" >
                <div class= "container" style="margin: 20px;">
                    <div class = "login"style="padding: 20px;">
                        
                        <h1 style="text-align: center;">Register</h1>  

                            <form method="POST" >  
                                {% csrf_token %}  
                                <table>  
                                    {{ form.as_table }}  
                                </table>  
                                <input type="submit" name="submit" value="Daftar"style= "border-radius: 4px;border:none;color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%;height:35px;margin-top:10px"></td>
                            </form>
                            

                        {% if messages %}  
                            <ul>   
                                {% for message in messages %}  
                                    <li>{{ message }}</li>  
                                    {% endfor %}  
                            </ul>   
                        {% endif %}

                    </div>
                </div>  
            </div>
        </div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <style>
            .atas{
                height: 25%;
                width: 100%;
                position: static;
                
            }
            .bawah{
                width: 100%;
                height: 25%;
                position: static;
            }
            .center {
                margin-top: 10px;
                position: absolute;
                height: 30px;
                width: 99%;
                left: 50%;
                -ms-transform: translate(-50%, -50%);
                transform: translate(-50%, -50%);
            
            }
            .button1{
                height: 100%;
                width: 100%;
                background-color:bisque;
                color: black;
            }
            .button2{
                margin-top: 20px;
                height: 30px;
                width: 100%;
                background-color:rgb(238, 34, 34);
                color: rgb(255, 255, 255);
            }
            .button3{
                margin-top: 0px;
                height: 30px;
                width: 100%;
                background-color:rgb(62, 143, 220);
                color: rgb(255, 255, 255);
            }
            .buttonjenis{
                background-color: rgb(255, 255, 255);
            }
            button:focus {
                outline: none;
                border: 1px solid black;
            }
            #q1button:focus {
                background-color: green;
                color: pink;
            }
            .list-group-item:focus{
                background-color: rgb(50, 59, 218);
                color: rgb(255, 255, 255);
            }
            
        </style>
    </head>

    <body style="position: static;max-height: 100%;">
        {% block content %}
        {% endblock content %}
    </body>
</html>